{
    "name": "Rubio SILICIE Report",
    "version": "18.0.1.0.0",
    "summary": "Exportación CSV SILICIE 2.0 de entregas (n.º de sílice como primera columna).",
    "author": "Ivan Parrado, Manuel Calero, Xtendoo SLU",
    "website": "https://xtendoo.es",
    "category": "Inventory/Reporting",
    "license": "LGPL-3",
    "depends": [
        "stock",
        "sale",
        "sale_stock",
        "rubio_stock_picking_silice_sequence",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/actions.xml",
        "views/res_config_settings_view.xml",
        "views/product_template_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/silice_report_wizard_views.xml",
        "views/menuitems.xml",
    ],
    "installable": True,
    "application": False,
}
